CartPole-v1:
  n_timesteps: 500000
  policy: 'MlpPolicy'
  learning_rate: 5.e-4
  batch_size: 32
  buffer_size: 200000
  learning_starts: 100
  gamma: 0.99
  target_update_interval: 10000
  train_freq: 4
  gradient_steps: 1
  exploration_fraction: 0.15
  exploration_final_eps: 0.05
  policy_kwargs: dict(net_arch=[256, 256])