CartPole-v1:
  n_timesteps: 100000
  policy: 'MlpPolicy'
  learning_rate: 1.e-4
  batch_size: 64
  buffer_size: 100000 
  learning_starts: 500
  gamma: 0.99
  target_update_interval: 100
  train_freq: 128
  gradient_steps: 1
  exploration_fraction: 0.15
  exploration_final_eps: 0.05
  policy_kwargs: dict(net_arch=[256, 256])