CartPole-v1:
  n_timesteps: 100000
  policy: 'MlpPolicy'
  learning_rate: 5.e-5
  batch_size: 32
  buffer_size: 100000
  learning_starts: 100
  gamma: 0.99
  target_update_interval: 10000
  train_freq: 4
  gradient_steps: 1
  exploration_fraction: 0.1
  exploration_final_eps: 0.05
  policy_kwargs: "dict(net_arch=[256, 256])"