CartPole-v1:
  batch_size: 128
  buffer_size: 150000
  exploration_final_eps: 0.025230688888157955
  exploration_fraction: 0.11003829144173587
  gamma: 0.99
  gradient_steps: 128
  learning_rate: 0.0008400878820135611
  learning_starts: 200
  n_timesteps: 100000
  policy: MlpPolicy
  policy_kwargs: dict(net_arch=[256, 256])
  target_update_interval: 10
  train_freq: 64
